{% set name = "pyirf" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyirf-{{ version }}.tar.gz
  sha256: 8ae593767d9a765bfa4202e9ee42def583490b4f0bc9cbd0d98c563d05f3f251

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - astropy >=5.3
    - matplotlib-base
    - numpy >=1.18
    - scipy
    - tqdm
    - setuptools-scm

test:
  imports:
    - pyirf
  commands:
    - pip check
    # check setuptools-scm version works
    - python -c "from pyirf import __version__; assert '0.0.0' not in __version__"
  requires:
    - pip

about:
  home: https://github.com/cta-observatory/pyirf
  summary: A python library to calculate IACT IRFs and Sensitivities
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maxnoe
    - HealthyPear
