{% set name = "pyirf" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyirf-{{ version }}.tar.gz
  sha256: a811f51219fe3bce550fded6eca3c25c840845b119112281277a746368da1fd1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - astropy >=4.0.2
    - matplotlib-base
    - numpy >=1.18
    - scipy
    - tqdm
    - setuptools-scm

test:
  imports:
    - pyirf
  commands:
    - pip check
    # check setuptools-scm version works
    - python -c "from pyirf import __version__; assert '0.0.0' not in __version__"
  requires:
    - pip

about:
  home: https://github.com/cta-observatory/pyirf
  summary: A python library to calculate IACT IRFs and Sensitivities
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maxnoe
    - HealthyPear
